apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamondappdeployment
  labels:
    app: diamondappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diamondappdeployment
  template:
    metadata:
      labels:
        app: diamondappdeployment
    spec:
      containers:
      - name: diamondcontainer
        image: 861276106382.dkr.ecr.us-east-1.amazonaws.com/diamondimage:1.6
        ports:
        - containerPort: 8080